# Generated by Django 2.1.5 on 2019-02-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_auto_20190206_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditfundmodel',
            name='is_returnable',
            field=models.BooleanField(default=False),
        ),
    ]
