# Generated by Django 2.1.5 on 2019-02-05 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenditureHeadingHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_heading_name', models.CharField(max_length=122)),
                ('new_heading_name', models.CharField(max_length=122)),
                ('old_description', models.TextField(blank=True, null=True)),
                ('new_description', models.TextField(blank=True, null=True)),
                ('old_uuid', models.UUIDField()),
                ('is_updated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_restored', models.BooleanField(default=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenditure_headings_history', to=settings.AUTH_USER_MODEL)),
                ('base_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenditure_headings_history', to='base_user.BaseUserModel')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenditureHeadingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(unique=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('base_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenditure_headings', to='base_user.BaseUserModel')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenditureRecordHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_expend_by', models.CharField(max_length=100)),
                ('new_expend_by', models.CharField(max_length=100)),
                ('old_description', models.TextField(blank=True, null=True)),
                ('new_description', models.TextField(blank=True, null=True)),
                ('old_amount', models.PositiveIntegerField()),
                ('new_amount', models.PositiveIntegerField()),
                ('old_is_verified', models.BooleanField(default=False)),
                ('new_is_verified', models.BooleanField(default=False)),
                ('old_expend_date', models.DateField()),
                ('new_expend_date', models.DateField()),
                ('old_uuid', models.UUIDField()),
                ('is_updated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_restored', models.BooleanField(default=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenditure_records_history', to=settings.AUTH_USER_MODEL)),
                ('base_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='all_expenditure_records_history', to='base_user.BaseUserModel')),
                ('new_expend_heading', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='new_all_records_history', to='expenditure.ExpenditureHeadingModel')),
                ('old_expend_heading', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='old_all_records_history', to='expenditure.ExpenditureHeadingModel')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenditureRecordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expend_by', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('expend_date', models.DateField()),
                ('uuid', models.UUIDField(unique=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_for_refund', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenditure_records', to=settings.AUTH_USER_MODEL)),
                ('base_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='all_expenditure_records', to='base_user.BaseUserModel')),
                ('expend_heading', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='all_records', to='expenditure.ExpenditureHeadingModel')),
            ],
        ),
        migrations.AddField(
            model_name='expenditurerecordhistorymodel',
            name='related_records',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_history', to='expenditure.ExpenditureRecordModel'),
        ),
        migrations.AddField(
            model_name='expenditureheadinghistorymodel',
            name='related_heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='all_history', to='expenditure.ExpenditureHeadingModel'),
        ),
    ]
