# Generated by Django 2.1.5 on 2019-02-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditurerecordmodel',
            name='is_for_return',
            field=models.BooleanField(default=False),
        ),
    ]
