# Generated by Django 2.1.5 on 2019-02-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0002_expenditurerecordmodel_is_for_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditurerecordmodel',
            name='is_verified_once',
            field=models.BooleanField(default=True),
        ),
    ]
