# Generated by Django 2.1.5 on 2019-02-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0003_expenditurerecordmodel_is_verified_once'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditurerecordmodel',
            name='is_verified_once',
            field=models.BooleanField(default=False),
        ),
    ]
