# Generated by Django 2.1.5 on 2019-02-05 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('accounts', 'Accounts'), ('co_admin', 'Co-Admin')], default='accounts', max_length=45)),
                ('uuid', models.UUIDField(unique=True)),
                ('joined', models.DateField(blank=True)),
                ('canAdd', models.BooleanField(default=True)),
                ('canRetrieve', models.BooleanField(default=False)),
                ('canEdit', models.BooleanField(default=False)),
                ('canList', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('base_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_users', to='base_user.BaseUserModel')),
                ('root_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='root_sub_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
