# Generated by Django 2.1.5 on 2019-02-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfomodel',
            name='title',
            field=models.TextField(default='100% Export Oriented Sweater Factory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyinfomodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
