# Generated by Django 2.1.5 on 2019-02-05 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_user', '0001_initial'),
        ('expenditure', '0001_initial'),
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditFundOnLoanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_funds', to='base_user.BaseUserModel')),
                ('credit_fund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='credit.CreditFundModel')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenditureRecordOnLoanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_refunds', to='base_user.BaseUserModel')),
                ('expenditure_record_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='expenditure.ExpenditureRecordModel')),
            ],
        ),
    ]
