# Generated by Django 2.1.5 on 2019-02-05 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtraInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_not_locked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('base_user', models.BooleanField(default=False)),
                ('sub_user', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_extra_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
